name = "lsp_log_analyzer"
version = "0.1.0"
defaultTargets = ["lsp_log_analyzer"]

[leanOptions]
experimental.module = true

[[lean_lib]]
name = "LSPLogAnalyzer"

[[lean_exe]]
name = "lsp_log_analyzer"
root = "Main"
